/* hk_banks.js — 香港銀行清算代碼（HKICL，2024-11 政府參考表） */
const HK_BANKS = [
  { code: '003', zh: '渣打銀行(香港)有限公司', en: 'Standard Chartered Bank (Hong Kong) Limited' },
  { code: '004', zh: '香港上海匯豐銀行有限公司', en: 'The Hongkong and Shanghai Banking Corporation Limited' },
  { code: '005', zh: '', en: 'Credit Agricole Corporate and Investment Bank' },
  { code: '006', zh: '花旗銀行', en: 'Citibank, N.A.' },
  { code: '007', zh: '', en: 'JPMorgan Chase Bank, N.A.' },
  { code: '009', zh: '中國建設銀行(亞洲)股份有限公司', en: 'China Construction Bank (Asia) Corporation Limited' },
  { code: '012', zh: '中國銀行(香港)有限公司', en: 'Bank of China (Hong Kong) Limited' },
  { code: '015', zh: '東亞銀行有限公司', en: 'The Bank of East Asia, Limited' },
  { code: '016', zh: '星展銀行(香港)有限公司', en: 'DBS Bank (Hong Kong) Limited' },
  { code: '018', zh: '中信銀行(國際)有限公司', en: 'China CITIC Bank International Limited' },
  { code: '020', zh: '招商永隆銀行有限公司', en: 'CMB Wing Lung Bank Limited' },
  { code: '022', zh: '', en: 'Oversea-Chinese Banking Corporation Ltd.' },
  { code: '024', zh: '恒生銀行有限公司', en: 'Hang Seng Bank Ltd.' },
  { code: '025', zh: '上海商業銀行有限公司', en: 'Shanghai Commercial Bank Ltd.' },
  { code: '027', zh: '交通銀行股份有限公司', en: 'Bank of Communications Co., Ltd' },
  { code: '028', zh: '大眾銀行(香港)有限公司', en: 'Public Bank (Hong Kong) Limited' },
  { code: '035', zh: '華僑銀行(香港)有限公司', en: 'OCBC Bank (Hong Kong) Limited' },
  { code: '038', zh: '大有銀行有限公司', en: 'Tai Yau Bank Ltd' },
  { code: '039', zh: '集友銀行有限公司', en: 'Chiyu Banking Corporation Ltd.' },
  { code: '040', zh: '大新銀行有限公司', en: 'Dah Sing Bank, Ltd.' },
  { code: '041', zh: '創興銀行有限公司', en: 'Chong Hing Bank Limited' },
  { code: '043', zh: '南洋商業銀行有限公司', en: 'Nanyang Commercial Bank, Ltd.' },
  { code: '045', zh: '', en: 'UCO Bank' },
  { code: '046', zh: '', en: 'KEB Hana Bank' },
  { code: '047', zh: '', en: 'MUFG Bank, Ltd.' },
  { code: '049', zh: '', en: 'Bangkok Bank Public Company Limited' },
  { code: '050', zh: '', en: 'Indian Overseas Bank' },
  { code: '054', zh: '', en: 'Deutsche Bank AG' },
  { code: '055', zh: '', en: 'Bank of America, National Association' },
  { code: '056', zh: '', en: 'BNP Paribas' },
  { code: '058', zh: '', en: 'Bank of India' },
  { code: '060', zh: '', en: 'National Bank of Pakistan' },
  { code: '061', zh: '大生銀行有限公司', en: 'Tai Sang Bank Limited' },
  { code: '063', zh: '馬來亞銀行', en: 'Malayan Banking Berhad (Maybank)' },
  { code: '065', zh: '', en: 'Sumitomo Mitsui Banking Corporation' },
  { code: '066', zh: '', en: 'PT. Bank Negara Indonesia (Persero) Tbk.' },
  { code: '067', zh: '金融銀行有限公司', en: 'BDO Unibank, Inc.' },
  { code: '071', zh: '大華銀行有限公司', en: 'United Overseas Bank Ltd.' },
  { code: '072', zh: '中國工商銀行(亞洲)有限公司', en: 'Industrial and Commercial Bank of China (Asia) Limited' },
  { code: '074', zh: '', en: 'Barclays Bank Plc.' },
  { code: '076', zh: '', en: 'The Bank of Nova Scotia' },
  { code: '080', zh: '加拿大皇家銀行', en: 'Royal Bank of Canada' },
  { code: '081', zh: '法國興業銀行', en: 'Societe Generale' },
  { code: '082', zh: '', en: 'State Bank of India' },
  { code: '085', zh: '多倫多道明銀行', en: 'The Toronto-Dominion Bank' },
  { code: '086', zh: '', en: 'Bank of Montreal' },
  { code: '092', zh: '加拿大帝國商業銀行', en: 'Canadian Imperial Bank of Commerce' },
  { code: '103', zh: '', en: 'UBS AG, Hong Kong' },
  { code: '106', zh: '美國滙豐銀行', en: 'HSBC Bank USA, National Association' },
  { code: '109', zh: '', en: 'Mizuho Bank, Ltd.' },
  { code: '113', zh: '', en: 'DZ Bank AG Deutsche Zentral-Genossenschaftsbank' },
  { code: '118', zh: '友利銀行', en: 'Woori Bank' },
  { code: '119', zh: '', en: 'Philippine National Bank' },
  { code: '128', zh: '富邦銀行(香港)有限公司', en: 'Fubon Bank (Hong Kong) Limited' },
  { code: '138', zh: '', en: 'Mitsubishi UFJ Trust and Banking Corporation' },
  { code: '139', zh: '', en: 'The Bank of New York Mellon' },
  { code: '145', zh: '', en: 'ING Bank N.V.' },
  { code: '147', zh: '', en: 'Banco Bilbao Vizcaya Argentaria, S.A.' },
  { code: '150', zh: '澳大利亞國民銀行', en: 'National Australia Bank Limited' },
  { code: '152', zh: '澳新銀行集團有限公司', en: 'Australia and New Zealand Banking Group Ltd.' },
  { code: '153', zh: '澳洲聯邦銀行', en: 'Commonwealth Bank of Australia' },
  { code: '161', zh: '意大利聯合聖保羅銀行股份有限公司', en: 'Intesa Sanpaolo S.p.A.' },
  { code: '164', zh: '裕信(德國)銀行股份有限公司', en: 'UniCredit Bank AG' },
  { code: '170', zh: '', en: 'The Chiba Bank Ltd' },
  { code: '178', zh: '比利時聯合銀行', en: 'KBC Bank N.V.' },
  { code: '180', zh: '', en: 'Wells Fargo Bank, N.A.' },
  { code: '183', zh: '', en: 'Coöperatieve Rabobank U.A.' },
  { code: '185', zh: '', en: 'DBS Bank Ltd, Hong Kong Branch' },
  { code: '186', zh: '靜岡銀行', en: 'The Shizuoka Bank Ltd.' },
  { code: '198', zh: '華南商業銀行股份有限公司', en: 'Hua Nan Commercial Bank Ltd.' },
  { code: '199', zh: '', en: 'The Shiga Bank, Ltd.' },
  { code: '201', zh: '臺灣銀行股份有限公司', en: 'Bank of Taiwan' },
  { code: '202', zh: '', en: 'The Chugoku Bank Limited' },
  { code: '203', zh: '第一商業銀行股份有限公司', en: 'First Commercial Bank' },
  { code: '206', zh: '彰化商業銀行股份有限公司', en: 'Chang Hwa Commercial Bank Ltd.' },
  { code: '210', zh: '', en: 'Natixis' },
  { code: '214', zh: '中國工商銀行股份有限公司', en: 'Industrial and Commercial Bank of China Limited' },
  { code: '220', zh: '', en: 'State Street Bank and Trust Company' },
  { code: '221', zh: '中國建設銀行股份有限公司', en: 'China Construction Bank Corporation' },
  { code: '222', zh: '中國農業銀行股份有限公司', en: 'Agricultural Bank of China Limited' },
  { code: '227', zh: '', en: 'Erste Group Bank AG' },
  { code: '229', zh: '中國信託商業銀行股份有限公司', en: 'CTBC Bank Co., Ltd.' },
  { code: '230', zh: '臺灣中小企業銀行股份有限公司', en: 'Taiwan Business Bank, Ltd.' },
  { code: '236', zh: '國泰世華商業銀行股份有限公司', en: 'Cathay United Bank Company, Limited' },
  { code: '237', zh: '瑞士盈豐銀行股份有限公司', en: 'EFG Bank AG' },
  { code: '238', zh: '招商銀行股份有限公司', en: 'China Merchants Bank Co., Ltd.' },
  { code: '239', zh: '台北富邦商業銀行股份有限公司', en: 'Taipei Fubon Commercial Bank Co., Ltd.' },
  { code: '241', zh: '永豐商業銀行股份有限公司', en: 'Bank SinoPac' },
  { code: '242', zh: '兆豐國際商業銀行股份有限公司', en: 'Mega International Commercial Bank Co., Ltd.' },
  { code: '243', zh: '玉山商業銀行股份有限公司', en: 'E.Sun Commercial Bank, Ltd.' },
  { code: '245', zh: '台新國際商業銀行股份有限公司', en: 'Taishin International Bank Co., Ltd.' },
  { code: '248', zh: '豐隆銀行有限公司', en: 'Hong Leong Bank Berhad' },
  { code: '249', zh: '渣打銀行', en: 'Standard Chartered Bank Hong Kong Branch' },
  { code: '250', zh: '花旗銀行(香港)有限公司', en: 'Citibank (Hong Kong) Limited' },
  { code: '251', zh: '', en: 'ICICI Bank Limited' },
  { code: '254', zh: '', en: 'Melli Bank plc' },
  { code: '258', zh: '華美銀行', en: 'East West Bank' },
  { code: '260', zh: '遠東國際商業銀行股份有限公司', en: 'Far Eastern International Bank' },
  { code: '263', zh: '國泰銀行', en: 'Cathay Bank' },
  { code: '264', zh: '臺灣土地銀行股份有限公司', en: 'Land Bank of Taiwan Co., Ltd.' },
  { code: '265', zh: '合作金庫商業銀行股份有限公司', en: 'Taiwan Cooperative Bank, Ltd.' },
  { code: '267', zh: '西班牙桑坦德銀行有限公司', en: 'Banco Santander S.A.' },
  { code: '269', zh: '上海商業儲蓄銀行股份有限公司', en: 'The Shanghai Commercial & Savings Bank Ltd.' },
  { code: '271', zh: '', en: 'Industrial Bank of Korea' },
  { code: '272', zh: '新加坡銀行有限公司', en: 'Bank of Singapore Limited' },
  { code: '273', zh: '', en: 'Shinhan Bank' },
  { code: '274', zh: '王道商業銀行股份有限公司', en: 'O-Bank Co., Ltd' },
  { code: '276', zh: '國家開發銀行', en: 'China Development Bank' },
  { code: '277', zh: '', en: 'First Abu Dhabi Bank PJSC' },
  { code: '278', zh: '', en: 'Bank J. Safra Sarasin Ltd.' },
  { code: '308', zh: '', en: 'HDFC Bank Limited' },
  { code: '309', zh: '', en: 'Union Bancaire Privee, UBP SA' },
  { code: '316', zh: '', en: 'Skandinaviska Enskilda Banken AB' },
  { code: '320', zh: '', en: 'Bank Julius Baer & Co. Ltd.' },
  { code: '324', zh: '法國工商銀行', en: 'Credit Industriel et Commercial' },
  { code: '337', zh: '臺灣新光商業銀行股份有限公司', en: 'Taiwan Shin Kong Commercial Bank Co., Ltd.' },
  { code: '338', zh: '中國銀行股份有限公司', en: 'Bank of China Limited, Hong Kong Branch' },
  { code: '339', zh: '', en: 'CA Indosuez (Switzerland) SA' },
  { code: '342', zh: 'LGT皇家銀行(香港)', en: 'LGT Bank AG' },
  { code: '345', zh: '上海浦東發展銀行股份有限公司', en: 'Shanghai Pudong Development Bank Co., Ltd.' },
  { code: '353', zh: '中國民生銀行股份有限公司', en: 'China Minsheng Banking Corp., Ltd.' },
  { code: '359', zh: '廣發銀行股份有限公司', en: 'China Guangfa Bank Co., Ltd.' },
  { code: '361', zh: '渤海銀行股份有限公司', en: 'China Bohai Bank Co., Ltd.' },
  { code: '364', zh: '', en: 'Banque Pictet & Cie SA' },
  { code: '365', zh: '東莞銀行股份有限公司', en: 'Bank of Dongguan Co., Ltd' },
  { code: '368', zh: '中國光大銀行股份有限公司', en: 'China Everbright Bank Co., Ltd.' },
  { code: '371', zh: '', en: 'Sumitomo Mitsui Trust Bank, Limited' },
  { code: '372', zh: '上海銀行(香港)有限公司', en: 'Bank of Shanghai (Hong Kong) Limited' },
  { code: '374', zh: '', en: 'CIMB Bank Berhad' },
  { code: '376', zh: '', en: 'NongHyup Bank' },
  { code: '377', zh: '興業銀行股份有限公司', en: 'Industrial Bank Co., Ltd' },
  { code: '378', zh: '元大商業銀行股份有限公司', en: 'Yuanta Commercial Bank Co., Ltd.' },
  { code: '379', zh: '', en: 'Mashreq Bank - Public Shareholding Company' },
  { code: '381', zh: '', en: 'Kookmin Bank' },
  { code: '382', zh: '交通銀行(香港)有限公司', en: 'Bank of Communications (Hong Kong) Limited' },
  { code: '383', zh: '浙商銀行股份有限公司', en: 'China Zheshang Bank Co., Ltd.' },
  { code: '384', zh: '摩根士丹利銀行亞洲有限公司', en: 'Morgan Stanley Bank Asia Limited' },
  { code: '385', zh: '平安銀行股份有限公司', en: 'Ping An Bank Co., Ltd.' },
  { code: '386', zh: '華夏銀行股份有限公司', en: 'Hua Xia Bank Co., Limited' },
  { code: '387', zh: '眾安銀行有限公司', en: 'ZA Bank Limited' },
  { code: '388', zh: '理慧銀行有限公司', en: 'Livi Bank Limited' },
  { code: '389', zh: '', en: 'Mox Bank Limited' },
  { code: '390', zh: '匯立銀行有限公司', en: 'Welab Bank Limited' },
  { code: '391', zh: '富融銀行有限公司', en: 'Fusion Bank Limited' },
  { code: '392', zh: '', en: 'PAO Bank Limited' },
  { code: '393', zh: '螞蟻銀行(香港)有限公司', en: 'Ant Bank (Hong Kong) Limited' },
  { code: '394', zh: '卡塔爾國家銀行', en: 'Qatar National Bank (Q.P.S.C.)' },
  { code: '395', zh: '天星銀行有限公司', en: 'Airstar Bank Limited' },
  { code: '396', zh: '', en: 'The Korea Development Bank' },
  { code: '397', zh: '中信銀行股份有限公司', en: 'China CITIC Bank Corporation Limited' },
];

/** 糧期收款常用：主流本地銀行（下拉選單） */
const HK_BANKS_MAINSTREAM = [
  { code: '003', label: '渣打銀行（香港）' },
  { code: '004', label: '匯豐' },
  { code: '012', label: '中銀香港' },
  { code: '015', label: '東亞銀行' },
  { code: '016', label: '星展銀行（香港）' },
  { code: '018', label: '中信銀行（國際）' },
  { code: '020', label: '招商永隆銀行' },
  { code: '024', label: '恒生銀行' },
  { code: '025', label: '上海商業銀行' },
  { code: '027', label: '交通銀行' },
  { code: '028', label: '大眾銀行（香港）' },
  { code: '035', label: '華僑銀行（香港）' },
  { code: '039', label: '集友銀行' },
  { code: '040', label: '大新銀行' },
  { code: '041', label: '創興銀行' },
  { code: '043', label: '南洋商業銀行' },
  { code: '072', label: '工商銀行（亞洲）' },
  { code: '128', label: '富邦銀行（香港）' },
  { code: '250', label: '花旗銀行（香港）' },
  { code: '382', label: '交通銀行（香港）' },
];

const HK_BANK_BY_CODE = Object.fromEntries(HK_BANKS.map(b => [b.code, b]));
const HK_MAINSTREAM_BY_CODE = Object.fromEntries(HK_BANKS_MAINSTREAM.map(b => [b.code, b]));

function hkBankOptionLabel(bank) {
  const name = (bank.label || bank.shortZh || bank.zh || '').trim();
  if (name) return `${bank.code} — ${name.replace(/有限公司$/, '').replace(/\(香港\)/, '（香港）')}`;
  return `${bank.code}`;
}

function hkBankShortName(code) {
  const raw = String(code || '').trim();
  if (!raw) return '';
  const c = /^\d+$/.test(raw) ? raw.padStart(3, '0') : raw;
  const mainstream = HK_MAINSTREAM_BY_CODE[c];
  if (mainstream) return mainstream.label;
  const bank = HK_BANK_BY_CODE[c];
  if (!bank) return code || '';
  const zh = (bank.zh || '').trim();
  if (zh) return zh.replace(/有限公司$/, '').replace(/\(香港\)/, '（香港）');
  return c;
}

function hkBankMatchQuery(bank, q) {
  if (!q) return true;
  const hay = `${bank.code} ${bank.label || ''} ${bank.zh || ''} ${bank.en || ''}`.toLowerCase();
  return hay.includes(q);
}
